///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WebTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WebTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fff7f986-e986-49a6-becd-c8fb298d5cb9")]
    public partial class WebTestRepository : RepoGenBaseFolder
    {
        static WebTestRepository instance = new WebTestRepository();
        WebTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the WebTestRepository element repository.
        /// </summary>
        [RepositoryFolder("fff7f986-e986-49a6-becd-c8fb298d5cb9")]
        public static WebTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WebTestRepository() 
            : base("WebTestRepository", "/", null, 0, false, "fff7f986-e986-49a6-becd-c8fb298d5cb9", ".\\RepositoryImages\\WebTestRepositoryfff7f986.rximgres")
        {
            _applicationundertest = new WebTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

        string _item = "MacBook";

        /// <summary>
        /// Gets or sets the value of variable item.
        /// </summary>
        [TestVariable("e522d23c-9158-4e6e-bae6-bada2d302abd")]
        public string item
        {
            get { return _item; }
            set { _item = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fff7f986-e986-49a6-becd-c8fb298d5cb9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ffc3efaf-bcce-4e3e-9904-c7d20a660efc")]
        public virtual WebTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WebTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ffc3efaf-bcce-4e3e-9904-c7d20a660efc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemInfo;
            RepoItemInfo _priceofitemInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='demo.opencart.com']", parentFolder, 30000, null, false, "ffc3efaf-bcce-4e3e-9904-c7d20a660efc", "")
            {
                _itemInfo = new RepoItemInfo(this, "Item", ".//a[@innertext=$item]", "", 30000, null, "3e692ca5-828d-44a0-b9e4-b135470ee939");
                _priceofitemInfo = new RepoItemInfo(this, "priceofitem", ".//a[@innertext=$item]/parent::h4/following-sibling::p[2]/span", "", 30000, null, "53c69858-7e92-4933-9dff-5843f7d67e6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ffc3efaf-bcce-4e3e-9904-c7d20a660efc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ffc3efaf-bcce-4e3e-9904-c7d20a660efc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Item item.
            /// </summary>
            [RepositoryItem("3e692ca5-828d-44a0-b9e4-b135470ee939")]
            public virtual Ranorex.ATag Item
            {
                get
                {
                    return _itemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Item item info.
            /// </summary>
            [RepositoryItemInfo("3e692ca5-828d-44a0-b9e4-b135470ee939")]
            public virtual RepoItemInfo ItemInfo
            {
                get
                {
                    return _itemInfo;
                }
            }

            /// <summary>
            /// The priceofitem item.
            /// </summary>
            [RepositoryItem("53c69858-7e92-4933-9dff-5843f7d67e6a")]
            public virtual Ranorex.SpanTag priceofitem
            {
                get
                {
                    return _priceofitemInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The priceofitem item info.
            /// </summary>
            [RepositoryItemInfo("53c69858-7e92-4933-9dff-5843f7d67e6a")]
            public virtual RepoItemInfo priceofitemInfo
            {
                get
                {
                    return _priceofitemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
